--HOW TO CREATE DATABASE AND SET IT AS A DEFAULT

CREATE DATABASE startersql;
USE startersql;

--HOW TO CREATE TABLE IN A DATABASE;

CREATE TABLE users (
    id INT PRIMARY KEY IDENTITY(1,1),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    gender VARCHAR(10) CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    date_of_birth DATE,
    created_at DATETIME DEFAULT GETDATE()
);

--TO CHECK DATA IN A TABLE
SELECT * FROM users;

--HOW TO DELETE A DATABASE
USE master;
ALTER DATABASE startersql SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE startersql;